---
title: ''
output:
  html_document:
    code_folding: show
    toc: yes
editor_options:
  chunk_output_type: console
---

# Reading in data
```{r}
library(tidyverse)
theme_set(theme_minimal())

halldorsson_raw <- read.delim("./../data/halldorsson_2019.tsv", header = TRUE, sep = "\t")
```

```{r}
halldorsson_lean <- halldorsson_raw |> 
  filter(mutation_class_cpg %in% c("T>C", "C>T", "CpG>TpG", "C>G", "C>A", "T>A", "T>G")) |> 
  select(AGE_FATHER, Child, mutation_class_cpg)
```

# Grouping by Child column
```{r}
halldorsson_child <- halldorsson_lean |> 
  group_by(Child, mutation_class_cpg) |> 
  summarize(
    nr_of_mut = n()
  )
```

```{r}
halldorsson_child <- halldorsson_child |> 
  pivot_wider(names_from = mutation_class_cpg,
              values_from = nr_of_mut)

halldorsson_child[is.na(halldorsson_child)] <- 0
```

```{r}
halldorsson_child$total <- rowSums(halldorsson_child) - halldorsson_child$Child
```

```{r}
halldorsson_fract_child <- halldorsson_child |> 
  mutate_at(vars(-total, -Child), funs(./total)) |> 
  select(-total)
```

## Doing the linear/quadratic/cubic regression

## Plots
```{r
ggplot(halldorsson_fract_child, aes()) +
  
```

# Grouping by fathers' age instead of child
```{r}
halldorsson_father <- halldorsson_lean |> 
  group_by(AGE_FATHER, mutation_class_cpg) |> 
  summarize(
    nr_of_mut = n()
  )
```

```{r}
halldorsson_father <- halldorsson_father |> 
  pivot_wider(names_from = mutation_class_cpg,
              values_from = nr_of_mut)

halldorsson_father[is.na(halldorsson_father)] <- 0
```

```{r}
halldorsson_father$total <- rowSums(halldorsson_father) - halldorsson_father$AGE_FATHER
```

```{r}
halldorsson_fract_father <- halldorsson_father |> 
  mutate_at(vars(-total, -AGE_FATHER), funs(./total)) |> 
  select(-total)
```

## Linear, quadratic, cubic regression model
```{r}
linear <- lm(AGE_FATHER ~ ., data = halldorsson_fract_father)

quadratic <- lm(AGE_FATHER ~ `C>A` + `C>G` + `C>T` + `CpG>TpG` + `T>C` + `T>G` + `T>A` + I(`C>A`^2)
                + I(`C>G`^2) + I(`C>T`^2) + I(`CpG>TpG`^2) + I(`T>C`^2) + I(`T>G`^2) + I(`T>A`^2),
                data = halldorsson_fract_father)

cubic <- lm(AGE_FATHER ~ `C>A` + `C>G` + `C>T` + `CpG>TpG` + `T>C` + `T>G` + `T>A` + I(`C>A`^2)
            + I(`C>G`^2) + I(`C>T`^2) + I(`CpG>TpG`^2) + I(`T>C`^2) + I(`T>G`^2) + I(`T>A`^2)
            + I(`C>G`^3) + I(`C>T`^3) + I(`CpG>TpG`^3) + I(`T>C`^3) + I(`T>G`^3) + I(`T>A`^3),
            data = halldorsson_fract_father)
```

```{r}
summary(linear)

summary(quadratic)

summary(cubic)
```

```{r}
linear_ca <- lm(`C>A` ~ AGE_FATHER, data = halldorsson_fract_father)

pred <- predict(linear_ca, data = halldorsson_fract_father)

halldorsson_fract_father$predicted <- pred

halldorsson_fract_father |> 
  ggplot(aes(x = AGE_FATHER, y = `C>A`)) +
  geom_point() +
  geom_smooth(aes(y = predicted))
```


## Plots linear
```{r}
library(patchwork)

p1 <- ggplot(halldorsson_fract_father, aes(x = AGE_FATHER, y = `C>A`)) +
  geom_point() +
  geom_smooth(method = "lm") +
  xlab("Fathers' Age")

p2 <- ggplot(halldorsson_fract_father, aes(x = AGE_FATHER, y = `C>G`)) +
  geom_point() +
  geom_smooth(method = "lm") +
  xlab("Fathers' Age")

p3 <- ggplot(halldorsson_fract_father, aes(x = AGE_FATHER, y = `C>T`)) +
  geom_point() +
  geom_smooth(method = "lm") +
  xlab("Fathers' Age")

p4 <- ggplot(halldorsson_fract_father, aes(x = AGE_FATHER, y = `CpG>TpG`)) +
  geom_point() +
  geom_smooth(method = "lm") +
  xlab("Fathers' Age")

p5 <- ggplot(halldorsson_fract_father, aes(x = AGE_FATHER, y = `T>C`)) +
  geom_point() +
  geom_smooth(method = "lm") +
  xlab("Fathers' Age")

p6 <- ggplot(halldorsson_fract_father, aes(x = AGE_FATHER, y = `T>G`)) +
  geom_point() +
  geom_smooth(method = "lm") +
  xlab("Fathers' Age")

p7 <- ggplot(halldorsson_fract_father, aes(x = AGE_FATHER, y = `T>A`)) +
  geom_point() +
  geom_smooth(method = "lm") +
  xlab("Fathers' Age")

p1 + p2 + p3 + p4 + p5 + p6 + p7
```

## Plots quadratic
```{r}
p1 <- ggplot(halldorsson_fract_father, aes(x = AGE_FATHER, y = `C>A`)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ poly(x, 2)) +
  xlab("Fathers' Age")

p2 <- ggplot(halldorsson_fract_father, aes(x = AGE_FATHER, y = `C>G`)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ poly(x, 2)) +
  xlab("Fathers' Age")

p3 <- ggplot(halldorsson_fract_father, aes(x = AGE_FATHER, y = `C>T`)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ poly(x, 2)) +
  xlab("Fathers' Age")

p4 <- ggplot(halldorsson_fract_father, aes(x = AGE_FATHER, y = `CpG>TpG`)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ poly(x, 2)) +
  xlab("Fathers' Age")

p5 <- ggplot(halldorsson_fract_father, aes(x = AGE_FATHER, y = `T>C`)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ poly(x, 2)) +
  xlab("Fathers' Age")

p6 <- ggplot(halldorsson_fract_father, aes(x = AGE_FATHER, y = `T>G`)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ poly(x, 2)) +
  xlab("Fathers' Age")

p7 <- ggplot(halldorsson_fract_father, aes(x = AGE_FATHER, y = `T>A`)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ poly(x, 2)) +
  xlab("Fathers' Age")

p1 + p2 + p3 + p4 + p5 + p6 + p7
```

## Plots cubic
```{r}
p1 <- ggplot(halldorsson_fract_father, aes(x = AGE_FATHER, y = `C>A`)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ poly(x, 3)) +
  xlab("Fathers' Age")

p2 <- ggplot(halldorsson_fract_father, aes(x = AGE_FATHER, y = `C>G`)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ poly(x, 3)) +
  xlab("Fathers' Age")

p3 <- ggplot(halldorsson_fract_father, aes(x = AGE_FATHER, y = `C>T`)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ poly(x, 3)) +
  xlab("Fathers' Age")

p4 <- ggplot(halldorsson_fract_father, aes(x = AGE_FATHER, y = `CpG>TpG`)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ poly(x, 3)) +
  xlab("Fathers' Age")

p5 <- ggplot(halldorsson_fract_father, aes(x = AGE_FATHER, y = `T>C`)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ poly(x, 3)) +
  xlab("Fathers' Age")

p6 <- ggplot(halldorsson_fract_father, aes(x = AGE_FATHER, y = `T>G`)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ poly(x, 3)) +
  xlab("Fathers' Age")

p7 <- ggplot(halldorsson_fract_father, aes(x = AGE_FATHER, y = `T>A`)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ poly(x, 3)) +
  xlab("Fathers' Age")

p1 + p2 + p3 + p4 + p5 + p6 + p7
```


